export enum StudentStatus {
  ENROLLED = 'ENROLLED',
  PENDING = 'PENDING',
  GRADUATED = 'GRADUATED',
  SUSPENDED = 'SUSPENDED',
}

export enum PaymentStatus {
  PAID = 'PAID',
  UNPAID = 'UNPAID',
  PARTIAL = 'PARTIAL',
}

export enum ApplicationStatus {
  REGISTRATION = 'REGISTRATION',
  DOCUMENT_SUBMISSION = 'DOCUMENT_SUBMISSION',
  DOCUMENT_REVIEW = 'DOCUMENT_REVIEW',
  DOCUMENTS_APPROVED = 'DOCUMENTS_APPROVED',
  SCHOLARSHIP_APPLICATION = 'SCHOLARSHIP_APPLICATION',
  APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
  SCHOOL_REVIEW = 'SCHOOL_REVIEW',
  SCHOOL_APPROVED = 'SCHOOL_APPROVED',
  PAYMENT = 'PAYMENT',
  ENROLLED = 'ENROLLED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum DocumentType {
  DIPLOMA = 'DIPLOMA',
  ID = 'ID',
  TRANSCRIPT = 'TRANSCRIPT',
  CERTIFICATE = 'CERTIFICATE',
  OTHER = 'OTHER',
}

export enum PaymentTxnStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum InquiryStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
}

export enum ActivityType {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  DOCUMENT = 'DOCUMENT',
  APPLICATION = 'APPLICATION',
  PAYMENT = 'PAYMENT',
  USER = 'USER',
  ROLE = 'ROLE',
  SYSTEM = 'SYSTEM',
}
