// Mirrors backend/types/permissions.ts — keep in sync with prisma/seed.ts's PERMISSIONS_BY_ROLE.
export const PERMISSIONS = {
  STUDENT_VIEW: "student:view",
  STUDENT_CREATE: "student:create",
  STUDENT_UPDATE: "student:update",
  STUDENT_DELETE: "student:delete",
  USER_VIEW: "user:view",
  USER_CREATE: "user:create",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  ROLE_VIEW: "role:view",
  ROLE_UPDATE: "role:update",
  DASHBOARD_VIEW: "dashboard:view",
  PAYMENT_VIEW: "payment:view",
  PAYMENT_CREATE: "payment:create",
  PAYMENT_UPDATE: "payment:update",
  PAYMENT_DELETE: "payment:delete",
  DOCUMENT_VIEW: "document:view",
  DOCUMENT_CREATE: "document:create",
  DOCUMENT_UPDATE: "document:update",
  DOCUMENT_DELETE: "document:delete",
  APPLICATION_VIEW: "application:view",
  APPLICATION_APPROVE: "application:approve",
  APPLICATION_REJECT: "application:reject",
  PARTNER_SCHOOL_VIEW: "partner_school:view",
  PARTNER_SCHOOL_CREATE: "partner_school:create",
  PARTNER_SCHOOL_UPDATE: "partner_school:update",
  PARTNER_SCHOOL_DELETE: "partner_school:delete",
  ACTIVITY_VIEW: "activity:view",
  SETTINGS_VIEW: "settings:view",
  SETTINGS_UPDATE: "settings:update",
  ID_CARD_VIEW: "id_card:view",
  ID_CARD_GENERATE: "id_card:generate",
  ID_CARD_REVOKE: "id_card:revoke",
} as const;

export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
