-- AlterTable
ALTER TABLE `applications` MODIFY `status` ENUM('REGISTRATION', 'DOCUMENT_SUBMISSION', 'DOCUMENT_REVIEW', 'DOCUMENTS_APPROVED', 'SCHOLARSHIP_APPLICATION', 'APPLICATION_SUBMITTED', 'SCHOOL_REVIEW', 'SCHOOL_APPROVED', 'PAYMENT', 'ENROLLED', 'PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'REGISTRATION';
